p8105\_hw1\_cm4070
================
Claire Mobley
2021-09-30

# Problem 1

### Create a data frame

*This code creates a data frame with numeric, logical, character, and
factor variables.*

``` r
set.seed(1234)

problem1_df = tibble(
  x = rnorm(10),
  vec_logical = x > 0, 
  vec_char = c("Hi", "my", "name", "is", "Claire", "Mobley", "nice", "to", "meet", "you"), 
  vec_factor = factor(c("red", "yellow", "green", "red", "yellow", "green", "yellow", "green", "green", "green"))
)

problem1_df
```

    ## # A tibble: 10 × 4
    ##         x vec_logical vec_char vec_factor
    ##     <dbl> <lgl>       <chr>    <fct>     
    ##  1 -1.21  FALSE       Hi       red       
    ##  2  0.277 TRUE        my       yellow    
    ##  3  1.08  TRUE        name     green     
    ##  4 -2.35  FALSE       is       red       
    ##  5  0.429 TRUE        Claire   yellow    
    ##  6  0.506 TRUE        Mobley   green     
    ##  7 -0.575 FALSE       nice     yellow    
    ##  8 -0.547 FALSE       to       green     
    ##  9 -0.564 FALSE       meet     green     
    ## 10 -0.890 FALSE       you      green

### Compute the mean of each variable

*This code attempts to compute the mean of x, vec\_logical, vec\_char,
and vec\_factor variables.*

``` r
library(tidyverse)

mean(pull(problem1_df, x))
```

    ## [1] -0.3831574

``` r
mean(pull(problem1_df, vec_logical))
```

    ## [1] 0.4

``` r
mean(pull(problem1_df, vec_char))
```

    ## [1] NA

``` r
mean(pull(problem1_df, vec_factor))
```

    ## [1] NA

-   The mean of x is -0.3831574

-   The mean of vec\_logical is 0.4

-   The mean of vec\_char is NA

-   The mean of vec\_factor is NA

The numeric and logical variables work.

The character and factor variables do not work.

### Convert variables

*This code attempts to convert the vec\_logical, vec\_char, and
vec\_factor variables to numeric form.*

``` r
as.numeric(pull(problem1_df, vec_logical))

as.numeric(pull(problem1_df, vec_char))

as.numeric(pull(problem1_df, vec_factor))
```

The as.numeric function creates a double-precision vector of the
specified length with each element as 0.

-   The logical vector turns into numericals with 0 as false and 1 as
    true.

-   The factor vector turns into numericals 1 through 3 for 3 levels.

-   The character vector is unable to be interpreted in numericals
    because it is only characters.

The factor and character means could not be computed because they are
either meaningless or cannot be made numerical.

# Problem 2

### New dataset

*This code will load the `penguins` dataset.*

``` r
data("penguins", package = "palmerpenguins")

penguins
```

    ## # A tibble: 344 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
    ##    <fct>   <fct>              <dbl>         <dbl>             <int>       <int>
    ##  1 Adelie  Torgersen           39.1          18.7               181        3750
    ##  2 Adelie  Torgersen           39.5          17.4               186        3800
    ##  3 Adelie  Torgersen           40.3          18                 195        3250
    ##  4 Adelie  Torgersen           NA            NA                  NA          NA
    ##  5 Adelie  Torgersen           36.7          19.3               193        3450
    ##  6 Adelie  Torgersen           39.3          20.6               190        3650
    ##  7 Adelie  Torgersen           38.9          17.8               181        3625
    ##  8 Adelie  Torgersen           39.2          19.6               195        4675
    ##  9 Adelie  Torgersen           34.1          18.1               193        3475
    ## 10 Adelie  Torgersen           42            20.2               190        4250
    ## # … with 334 more rows, and 2 more variables: sex <fct>, year <int>

### Description

-   `penguins` dataset contains 8 variables: species, island,
    bill\_length\_mm, bill\_depth\_mm, flipper\_length\_mm,
    body\_mass\_g, sex, year

-   contains 344 rows and 8 columns

-   the mean flipper length is 200.9152047

### Scatterplot

*This code will make a color coded scatter plot of flipper length
vs. bill length for the species variable.*

``` r
ggplot(penguins, aes(x = flipper_length_mm, y = bill_length_mm, color = species)) + geom_point()
```

![](p8105_hw1_cm4070_files/figure-gfm/ggplot_species-1.png)<!-- -->
